blog/urls.py
#coding:utf-8
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import *
from django.conf.urls.static import static
from django.conf import settings
from DjangoUeditor import urls as DjangoUeditor_urls
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include(DjangoUeditor_urls)),
    url(r'^$', ArticleView.as_view(), name='index'),
    url(r'^article/(?P<title>.*)$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^category/(?P<category>\S+)$', CategoryListView.as_view(), name='category'),
    url(r'^tag/(?P<tag>\S+)$', TagListView.as_view(), name='tag'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^message/$', MessageView.as_view(), name='message'),
    url(r'^me/$', Me.as_view(), name='me'),
]

django_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import *
from django.conf.urls.static import static
from django.conf import settings
import DjangoUeditor
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^$', ArticleView.as_view(), name='index'),
    url(r'^article/(?P<title>.*)$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^category/(?P<category>\S+)$', CategoryListView.as_view(), name='category'),
    url(r'^tag/(?P<tag>\S+)$', TagListView.as_view(), name='tag'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^message/$', MessageView.as_view(), name='message'),
    url(r'^me/$', Me.as_view(), name='me'),
]

urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
#coding:utf-8

from django.db import models
from DjangoUeditor.models import UEditorField
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.urlresolvers import reverse


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='标签名称')

    def get_absolute_url(self):
        return reverse('tag', args=[self.name])

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def articles_count(self):
        return self.articles.count()


# 文章分类
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称', unique=True)

    def get_absolute_url(self):
        return reverse('category', args=[self.name])

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题', unique=True)
    desc = models.CharField(max_length=50, verbose_name='文章描述')
    content=UEditorField()
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    category = models.ForeignKey(Category, blank=False, null=False, verbose_name='分类', to_field='name')
    tag = models.ManyToManyField(Tag, verbose_name='标签', related_name='articles')

    def get_absolute_url(self):
        return reverse('article_detail', args=[self.title])

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']
    class Media:
	js = (  
            '/static/js/tinymce/tinymce.min.js',  
            '/static/js/textareas.js',  
         )

    def __str__(self):
        return self.title

blog/views.py
#coding:utf-8
from .models import *

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView


class BaseListView(ListView):
    context_object_name = 'article_list'
    paginate_by = 5


class ArticleView(BaseListView):
    template_name = 'index.html'
    model = Article


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article.html'
    context_object_name = 'article'
    slug_url_kwarg = 'title'
    slug_field = 'title'

    def get_object(self, queryset=None):
        article = super(ArticleDetailView, self).get_object(queryset)
        article.click_count += 1
        article.save()
        return article

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)

        try:
            prev_article = Article.objects.filter(pk__lt=self.object.id).order_by('-pk')[0]
        except IndexError:
            prev_article = None
        try:
            next_article = Article.objects.filter(pk__gt=self.object.id).order_by('pk')[0]
        except IndexError:
            next_article = None

        context['prev_article'] = prev_article
        context['next_article'] = next_article
        return context


class CategoryListView(BaseListView):
    template_name = 'index.html'

    def get_queryset(self):
        queryset = Article.objects.filter(category=self.kwargs['category'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['is_category'] = True
        context['category'] = self.kwargs['category']
        return context


class TagListView(BaseListView):
    template_name = 'index.html'

    def get_queryset(self):
        queryset = Tag.objects.get(name=self.kwargs['tag']).articles.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context['is_tag'] = True
        context['tag'] = self.kwargs['tag']
        return context


class SearchView(BaseListView):
    template_name = 'index.html'

    def get_queryset(self):
        queryset = Article.objects.filter(title__icontains=self.request.GET.get('search'))
        return queryset


class Me(TemplateView):
    template_name = 'me.html'


class ArchiveView(BaseListView):
    template_name = 'archive.html'
    paginate_by = None

    def get_queryset(self):
        articles = Article.objects.all()
        for article in articles:
            article.yeah_month = article.date_publish.strftime('%Y-%m')
        return articles


class MessageView(TemplateView):
    template_name = 'message.html'

templates/archive.html
{% extends 'base.html' %}

{% block title %}
    文章归档|{{ site_name }}
{% endblock %}

{% block content %}
    <div class="panel">
        <div class="panel-heading navbar-default"><strong>归档</strong></div>
        <div class="panel-body">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#category" data-toggle="tab" class="left">分类</a></li>
                <li role="presentation"><a href="#tag" data-toggle="tab" class="left">标签</a></li>
                <li role="presentation"><a href="#time" data-toggle="tab" class="left">时间</a></li>
            </ul>
        </div>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="category">
            {% for a in categories %}
            <div class="panel">
                <div class="panel-heading"><strong>{{ a.name }}</strong></div>
                <div class="panel-body">
                    {% for article in a.article_set.all %}
                    <li class="col-md-12" style="list-style-type:none">
                        <a class="left" href="{{ article.get_absolute_url }}">
                            <span class="col-md-4">
                                <span class="glyphicon glyphicon-book"></span>《{{ article.title }}》
                            </span>
                            <span class="col-md-5">
                                <span class="glyphicon glyphicon-pencil"></span>描述：{{ article.desc }}
                            </span>
                            <span class="col-md-3">
                                <span class="glyphicon glyphicon-time"></span>时间：{{ article.date_publish | date:"SHORT_DATE_FORMAT" }}
                            </span>
                        </a>
                    </li>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="tab-pane fade" id="tag">
            {% for a in tag_list %}
            <div class="panel">
                <div class="panel-heading"><strong>{{ a.name }}</strong></div>
                <div class="panel-body">
                    {% for article in a.articles.all %}
                    <li class="col-md-12" style="list-style-type:none">
                        <a class="left" href="{{ article.get_absolute_url }}">
                            <span class="col-md-4">
                                <span class="glyphicon glyphicon-book"></span>《{{ article.title }}》
                            </span>
                            <span class="col-md-5">
                                <span class="glyphicon glyphicon-pencil"></span>描述：{{ article.desc }}
                            </span>
                            <span class="col-md-3">
                                <span class="glyphicon glyphicon-time"></span>时间：{{ article.date_publish | date:"SHORT_DATE_FORMAT" }}
                            </span>
                        </a>
                    </li>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="tab-pane fade" id="time">
        {% regroup article_list by yeah_month as list %}
            {% for article in list %}
            <div class="panel">
                <div class="panel-heading"><strong>{{ article.grouper }}</strong></div>
                <div class="panel-body">
                    {% for article in article.list %}
                    <li class="col-md-12" style="list-style-type:none">
                        <a class="left" href="{{ article.get_absolute_url }}">
                            <span class="col-md-4">
                                <span class="glyphicon glyphicon-book"></span>《{{ article.title }}》
                            </span>
                            <span class="col-md-5">
                                <span class="glyphicon glyphicon-pencil"></span>描述：{{ article.desc }}
                            </span>
                            <span class="col-md-3">
                                <span class="glyphicon glyphicon-time"></span>时间：{{ article.date_publish | date:"SHORT_DATE_FORMAT" }}
                            </span>
                        </a>
                    </li>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

    </div>

{% endblock %}

templates/article.html
{% extends 'base.html' %}

{% block title %}
    {{ article.title }}|{{ site_name }}
{% endblock %}
{% block content %}
    <div class="panel">
                <div class="panel-title text-center">    <!--文章标题-->
                    <a href="{{ content.get_absolute_url }}"><h2>{{ article.title }}</h2></a>
                </div>
                <div class="text-center">        <!--文章标签和时间-->
                    {% for tag in content.tag.all %}
                        <a href="{{ tag.get_absolute_url }}"> <span class="label label-default glyphicon glyphicon-tag">{{ tag }}</span> </a>
                    {% endfor %}
                    <span class="label label-default glyphicon glyphicon-calendar"> {{ article.date_publish | date:"SHORT_DATE_FORMAT" }}</span>
                </div>
            {% autoescape off %}
                <div class="panel-body">
                {{ article.content | safe }}
                </div>
            {% endautoescape %}
        </div>
        <div class="panel-body">
            {% if prev_article %}
            <a class="left" href="{{ prev_article.get_absolute_url }}"><span class="glyphicon glyphicon-chevron-left"></span>{{ prev_article.title }}</a>
            {% else %}
            <a class="left" href="#"><span class="glyphicon glyphicon-chevron-left"></span>无上一篇文章</a>
            {% endif %}
            <a class="left" href="#"><span class="glyphicon glyphicon-minus"></span></a>
            {% if next_article %}
            <a class="left" href="{{ next_article.get_absolute_url }}">{{ next_article.title }}<span class="glyphicon glyphicon-chevron-right"></span></a>
            {% else %}
            <a class="left" href="#">无下一篇文章<span class="glyphicon glyphicon-chevron-right"></span></a>
            {% endif %}
            <!--<div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
            
            <script>
            var cloudTieConfig = {
            sourceId: "{{ article.id }}",
            productKey: "e53fde77481e4060b1397ad284f5b835",
            target: "cloud-tie-wrapper"
            };
            var yunManualLoad = true;
            Tie.loader("aHR0cHM6Ly9hcGkuZ2VudGllLjE2My5jb20vcGMvbGl2ZXNjcmlwdC5odG1s", true);
            </script>
            </div>
            -->
        </div>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='{% static 'css/base.css' %}'>
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- 可选的Bootstrap主题文件（一般不用引入） -->
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href='{% static 'syntaxhighlighter/styles/shCoreDefault.css' %}'/>
    
    <!--script>tinymce.init({ selector:'textarea' });</script>-->
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/jquery/3.0.0-alpha1/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/jquery/3.0.0-alpha1/jquery.js"></script>
    <script src="{% static 'js/scrollup/jquery.scrollUp.js' %}"></script>
    <script src="https://img1.ws.126.net/f2e/tie/yun/sdk/loader.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
  
    <script src="{% static 'syntaxhighlighter/scripts/shCore.js' %}"></script>
    <script type="text/javascript">SyntaxHighlighter.all();</script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <script class="javascript" src='{% static 'syntaxhighlighter/scripts/shBrushJScript.js' %}'></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushBash.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushPhp.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushJava.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushSql.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushXml.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushPython.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushCss.js' %}"></script>
<script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushCpp.js' %}"></script>
    <div class="container-fluid">
        <nav class="navbar-collapse navbar navbar-default navbar-fixed-top container">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
                    <a class="navbar-brand" href="{% url 'index' %}">JH</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
        <li><a href="{% url 'index' %}">首页 <span class="sr-only">(current)</span></a></li>
		<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">文章分类 <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    {% for x in categories %}
                        <li><a href="{{ x.get_absolute_url }}">{{ x.name }}</a></li>
                    {% endfor %}
                </ul>
        </li>
        <li><a href="{% url 'message' %}">留言</a></li>
        <li><a href="{% url 'me' %}">关于我</a></li>
		<li><a href="{% url 'archive' %}">文章归档</a></li>
      </ul>
	  
      <form class="navbar-form navbar-right" role="search" action="/search/">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="" name="search">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>搜索</button>
      </form>
                </div>
            </div>
        </nav>
       
       <div class="page-header">
            <div class="row">
                <div class="container-fluid">
					<!--<img src="/static/image/dfz.jpg" class="img-responsive" alt="Responsive image">-->
                </div>
            </div>
        </div>
        <div class="row" id="bs-example-navbar-collapse-1">
            {% include 'left.html' %}
             <div class="col-md-9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
<hr>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    {% if is_category %}
    {{ category }}|{{ site_name }}
    {% elif is_tag %}
        {{ tag }}|{{ site_name }}
    {% elif is_search %}
        {{ title }}|{{ site_name }}
    {% else %}
        {{ site_name }}
    {% endif %}
{% endblock %}

{% block content %}
    {% if article_list %}
        {% for content in article_list %}
            <div class="panel">
                <div class="panel-title text-center">    <!--文章标题-->
                    <a href="{{ content.get_absolute_url }}"><h2>{{ content.title }}</h2></a>
                </div>
                <div class="text-center">        <!--文章标签和时间-->
                    {% for tag in content.tag.all %}
                        <a href="{{ tag.get_absolute_url }}"> <span class="label label-default glyphicon glyphicon-tag">{{ tag }}</span> </a>
                    {% endfor %}
                    <span class="label label-default glyphicon glyphicon-calendar"> {{ content.date_publish | date:"SHORT_DATE_FORMAT" }}</span>
                </div>
                {% autoescape off %}
                <div class="panel-body">  <!--文章内容-->
                    {{ content.content | truncatechars_html:100 }}<a class="label label-default" href="{% url 'article_detail' content.title %}">阅读全文</a>
                </div>
                {% endautoescape %}
            </div>
        {% endfor %}
    {% else %}
        <div class="panel">
            <div class="panel-heading navbar-default">
                <h3 class="panel-title">暫无文章!</h3>
            </div>
            <div class="panel-body">
                <p><center>
                    <br>
                
                </center></p>
                <br>
                <br>
            </div>
        </div>
    {% endif %}
{% include 'page.html' %}
{% endblock %}

templates/left.html
{% load staticfiles %}
<div class="col-md-3 catalog">
    <!--<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        </ol>

        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="{% static 'image/df.jpg' %}" alt="jing">
                <div class="carousel-caption">jing
                </div>
            </div>
            <div class="item">
                <img src="{% static 'image/ddwx.jpg' %}" alt="大道无形">
                <div class="carousel-caption">
                </div>
            </div>
            <div class="item">
                <img src="{% static 'image/jing.jpg' %}" alt="静">
                <div class="carousel-caption">静
                </div>
            </div>
            <div class="item">
                <img src="{% static 'image/ssrs.jpg' %}" alt="上善若水">
                <div class="carousel-caption">上善若水
                </div>
            </div>
            <div class="item">
                <img src="{% static 'image/cqcj.jpg' %}" alt="常清常静">
                <div class="carousel-caption">常清常静
                </div>
            </div>
        </div>
        
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    -->
    <div class="panel">
        <div class="panel-heading navbar-default"><strong>文章分类</strong></div>
        <div class="list-group">
            {% for x in categories %}
                <a class="list-group-item" href="{{ x.get_absolute_url }}">{{ x.name }}</a>
            {% endfor %}
        
        </div>
    </div>

    <div class="panel ">
        <div class="panel-heading navbar-default"><strong>标签</strong>
        </div>
        <div class="list-group">
                {% for tag in tag_list %}
                    <a href="{{ tag.get_absolute_url}}" class="list-group-item">{{ tag.name }}({{ tag.articles_count }})</a>
                {% endfor %}
        </div>
    </div>
  <!--  <div class="panel">
        <div class="panel-heading navbar-default"><strong>推荐文章</strong>
        </div>
        <div class="panel-body">
            <ul>
                {% for x in recommendation %}
                    <li><a href="{{ x.get_absolute_url }}" class="left">{{ x.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>-->
</div>

templates/me.html
{% extends 'base.html' %}

{% block title %}
    关于我|{{ site_name }}
{% endblock %}

{% block content %}
    <div class="panel">
        <div class="panel-heading navbar-default"><strong>时间</strong>
        </div>
        <div class="panel-body">
            <div class="container">
                <h4>
                     2017年1月1日
                </h4>
            </div>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading navbar-default"><strong>地点</strong>
        </div>
        <div class="panel-body">
            <div class="container">
                <h4>
                    北京市海淀区
                </h4>
            </div>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading navbar-default"><strong>人物</strong>
        </div>
        <div class="panel-body">
                <h4>
		   &nbsp&nbsp&nbsp&nbsp贾寒，男，地地道道的90后！为什么要创建自己的网站？在大二开始有记笔记的习惯，就开始在网上搜罗一些笔记软件，轻笔记、onenote、腾讯微云、51cto博客、开源中国博客、印象笔记、为知笔记等等！太散乱，记录之后就没有翻看过，无意义。所以，本博客成立！
                </h4>
            </div>
    </div>
{% endblock %}

templates/message.html
{% extends 'base.html' %}

{% block title %}
    留言|{{ site_name }}
{% endblock %}

{% block content %}
    <div class="panel">
        <div class="panel-heading navbar-default"><strong>留言栏</strong>
        </div>

       <!-- <div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
            <script>
            var cloudTieConfig = {
              sourceId: "message",
              productKey: "e53fde77481e4060b1397ad284f5b835",
              target: "cloud-tie-wrapper"
            };
            var yunManualLoad = true;
            Tie.loader("aHR0cHM6Ly9hcGkuZ2VudGllLjE2My5jb20vcGMvbGl2ZXNjcmlwdC5odG1s", true);
            </script>
        </div>
-->
	<!-- 多说评论框 start -->
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"51rain"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->

{% endblock %}

templates/page.html
<nav>
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li class="previous"><a href="?page={{ page_obj.previous_page_number  }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 上一页</a></li>
        {% else %}
            <li class="previous disabled"><a href="">上一页</a></li>
        {% endif %}
        <li>{{ page_obj.number  }} / {{ paginator.num_pages  }}</li>
        {% if page_obj.has_next %}
            <li class="next"><a href="?page={{ page_obj.next_page_number  }}">下一页 <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a></li>
        {% else %}
            <li class="next disabled"><a href="">下一页</a></li>
        {% endif %}
    </ul>
</nav>